{{- if or (contains "android" .osid) (contains "fedora" .osid) -}}
[".emacs.d"]
    type = "git-repo"
    url = "https://github.com/sgbonney/.emacs.d"

{{- else if contains "debian" .osid -}}
["Git/chezmoi"]
    type = "git-repo"
    url = "https://github.com/sgbonney/dotfiles"
    refreshPeriod = "24h"

["Git/emacs"]
    type = "git-repo"
    url = "https://github.com/sgbonney/.emacs.d"
    refreshPeriod = "24h"

["Git/fluidbuild"]
    type = "git-repo"
    url = "https://github.com/sgbonney/fluidbuild"
{{- end -}}

{{- if contains "linux" .osid -}} {{- "\n" }}
[".local/share/icons/syncthing.svg"]
    type = "file"
    url = "https://raw.githubusercontent.com/syncthing/syncthing/main/assets/logo-only.svg"
{{- end -}}