{{- if or (contains "android" .osid) (contains "fedora" .osid) -}}
[".emacs.d"]
    type = "git-repo"
    url = "https://github.com/sgbonney/.emacs.d"

{{-   if contains "fedora" .osid -}}  {{- "\n" }}
["{{- output "bash" "-c" "find ~/ -type d -path '*/calibre/plugins' -print" | trimPrefix .chezmoi.homeDir | trimPrefix "/" | trim -}}/DeACSM_{{ (gitHubLatestRelease "Leseratte10/acsm-calibre-plugin").TagName | trimPrefix "v" }}.zip"]
    type = "file"
    url = {{ gitHubLatestReleaseAssetURL "Leseratte10/acsm-calibre-plugin" "*.zip" | quote }}

["{{- output "bash" "-c" "find ~/ -type d -path '*/calibre/plugins' -print" | trimPrefix .chezmoi.homeDir | trimPrefix "/" | trim -}}/DeDRM_{{ (gitHubLatestRelease "noDRM/DeDRM_tools").TagName | trimPrefix "v" }}.zip"]
    type = "archive-file"
    url = {{ gitHubLatestReleaseAssetURL "noDRM/DeDRM_tools" "*.zip" | quote }}
    path = "DeDRM_plugin.zip"
{{-   end -}}

{{- else if contains "debian" .osid -}}
["Git/chezmoi"]
    type = "git-repo"
    url = "https://github.com/sgbonney/dotfiles"
    refreshPeriod = "24h"

["Git/emacs"]
    type = "git-repo"
    url = "https://github.com/sgbonney/.emacs.d"
    refreshPeriod = "24h"

["Git/fluidbuild"]
    type = "git-repo"
    url = "https://github.com/sgbonney/fluidbuild"
{{- end -}}

{{- if contains "linux" .osid -}} {{- "\n" }}
[".local/share/icons/syncthing.svg"]
    type = "file"
    url = "https://raw.githubusercontent.com/syncthing/syncthing/main/assets/logo-only.svg"
{{- end -}}