{{- if contains "linux" .osid -}}
[".local/share/icons/syncthing.svg"]
    type = "file"
    url = "https://raw.githubusercontent.com/syncthing/syncthing/main/assets/logo-only.svg"

{{-   if contains "fedora" .osid -}}{{- "\n" }}
{{ template "gitHub/downloadRelease" dict
    "target" ".var/app/com.calibre_ebook.calibre/config/calibre/plugins"
    "source" "Leseratte10/acsm-calibre-plugin"
    "type" "file" }}

{{ template "gitHub/downloadRelease" dict
    "target" ".var/app/com.calibre_ebook.calibre/config/calibre/plugins"
    "source" "noDRM/DeDRM_tools"
    "type" "archive-file"
    "path" "DeDRM_plugin.zip" }}

{{-   else if contains "debian" .osid -}}{{- "\n" }}
["Git/chezmoi"]
    type = "git-repo"
    url = "https://github.com/sgbonney/dotfiles"
    refreshPeriod = "24h"

["Git/fluidbuild"]
    type = "git-repo"
    url = "https://github.com/sgbonney/fluidbuild"
{{-   end }}
{{- end -}}