{{- if contains "linux" .osid -}}
{{-   if contains "fedora" .osid -}}
{{ template "gitHub/downloadRelease" dict "source" "Leseratte10/acsm-calibre-plugin" "target" "*/calibre/plugins" "type" "file" "chezmoi" .chezmoi }}

{{ template "gitHub/downloadRelease" dict "source" "noDRM/DeDRM_tools" "target" "*/calibre/plugins" "type" "archive-file" "path" "DeDRM_plugin.zip" "chezmoi" .chezmoi }}

{{-   else if contains "debian" .osid -}}
["Git/chezmoi"]
    type = "git-repo"
    url = "https://github.com/sgbonney/dotfiles"
    refreshPeriod = "24h"

["Git/fluidbuild"]
    type = "git-repo"
    url = "https://github.com/sgbonney/fluidbuild"
{{-   end }}

[".local/share/icons/syncthing.svg"]
    type = "file"
    url = "https://raw.githubusercontent.com/syncthing/syncthing/main/assets/logo-only.svg"
{{- end -}}