{{- if contains "fedora" .osid -}}
{{ template "gitHub/downloadRelease" dict
    "target" ".var/app/com.calibre_ebook.calibre/config/calibre/plugins"
    "source" "Leseratte10/acsm-calibre-plugin"
    "type" "file" }}

{{ template "gitHub/downloadRelease" dict
    "target" ".var/app/com.calibre_ebook.calibre/config/calibre/plugins"
    "source" "noDRM/DeDRM_tools"
    "type" "archive-file"
    "path" "DeDRM_plugin.zip" }}
{{- end -}}